project:
  type: website

website:
  title: "Tobias Nunn Undergrad Dissertation Project Notebook"
  navbar:
    right:
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

