project:
  type: book

book:
  title: "05_dissertation"
  author: "Tobias Nunn"
  date: "17/06/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - conclusion.qmd
    - references.qmd
  repo-url: https://github.com/tobiasnunn/tnunn_research/tree/main/Research_Experience_Module/07_portfolio
  repo-branch: main
  repo-actions: [issue]
  sidebar:
    search: false


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

