---
title: "Week 15 2025-10-20 to 2025-10-26"
author: "Tobias Nunn"
date: "2025-10-26"
categories:
---

# Introduction

*Brief overview of the week's objectives and context.*

This week, I want to continue to build up the pipeline, so that it is ready for the M. bovis samples from the NCBI to flush right through

# Methods

*Description of stuff I did.*

To do this, I am going to start with continuing my work from last week to add a small step to the pipeline. This will be an R script "reorder_annotations.R", ran from a slurm script I will likely call "Reorder_annotations_runner.sh". This will mean that, if I wish, I can use the high memory of Hawk to do this. Afterwards, the annotations will be in much easier-to-work-with groups for the next steps of the pipeline, thus why this is important to do. So, I will need to modify the script that is down wind of this change, but I will do that after. I modified the existing script "fastafile_getter_runner.sh", as it had many similarities. I ran it by doing another "sbatch" statement on the command line, and the usual stuff associated with that. After some trial and error, I got slightly stuck with slurm on this. The error file seems to imply that the singularity instance of R does not have the "here" package installed, which I use to do proper file paths, this is too big of an issue, for me to fix today, so I will resume this task another day. I was wrong about that, the code I copied was missing a colon in "here::here()". So, I am giving it one final go. On preliminary view, it looks like its working, so I am going to leave it and see how long it runs for. OK, I was wrong again, it crashed, I am not quite sure why it is failing, but I have run out of time for today, so I will have to debug another day. I was wrong for the 3rd time, I took one last look at it, to see if there was a glaring error I had somehow missed, there was. I had passed "directory", an object containing the file path to the location of the inputs, into the function I was using to create the directory structure of the outputs. In short, the function checked the path, saw it existed, and did nothing, leading to the error, when the output directory did not exist. I have fixed this now, lets hope this is the last time I have to write here today.

It appears to have run successfully, I will analyse the results at a later point in time. Then make sure the preceding script the outputs will be read into is updated. I had a look at the .out file and it looks like it only ran the loop twice.

Right, I have had a poke about in the files and I now know the problem. For the batches of 1500 and 2040, the contig_ID has been formatted weirdly. For example, "GCF_025144205.1_2JALXWZ010000001.1_2", instead of the usual "GCF_025144205.1_2". I am not sure why it has done this, but it means there is a problem with the code that creates the protein .fasta files, which I will need to go and fix. This, alongside fixing the part where I pull the accession ID out of the contig ID, for example, so it only works on the first (however many) characters. Also, I need to still update the pipeline after this fraught step so that it can take the new output 

# Results

*Key findings, observations, and data from this week's work.*

# Conclusion

*Summary of outcomes, implications, and next steps.*

# Scientific Papers

*Relevant literature read this week.*

-   

-   

-   
