---
title: "Week 9 2025-09-08 to 2025-09-14"
author: "Tobias Nunn"
date: "2025-09-14"
categories:
---

# Introduction

I am gonna start this with a plan of what I want to do in the Methods section. Largely, before term starts I want to have all of the accessions for the 5 genera of interest annotated using eggnog-mapper and then enriched for KEGG pathways.

# Methods

### Flow chart of data preparation / collection

```{mermaid}
flowchart TD
  A[define genera of interest] -->|get accession numbers| B(download accession metadata)
  B -->|get genomic information| C(download .fasta information)
  C --> D[convert genomic data to protein data]
  D --> E[combine fastas into large files]
  E --> F(perform eggnog-mapper search)
  F --> G(perform eggnog-mapper annotation)
  G --> H(perform KEGG enrichment)
  H --> I{{perform analysis}}
  B -->|enrich data for analyses| I
```

Those are the general stages. I still fear it may be too much to hold in my head at any one time, but at this point, I might as well just get on with it.

Ok, since last week, I have identified areas where the pipeline could be improved. As a list:

1.  my private information vis-a-vis the NCBI key has managed to get up onto github, so I am going to need to fix that
2.  I am not happy with the output metadata files being stored with the ID, as, when just looking at the files, I will have no earthly idea what genus the ID connects to
3.  Randomly, I came across a thing in R called rds. This purportes itself to be a more efficient way of data storage than saving them out as files to my disk. Now, doing whatever that means, would mean storing the metadata as some kind of R object on disk, which would circumvent the need for ID or genus name in the title, addressing point 2. However, it would be good to include the genus name in the object, so I may do the thing I was going to do to address point 2 anyway, just because it is still useful to a degree. also because it is very clever as it would prerequisite doing an API call inside of a function that already does and API call.

specifically, I found out about rds [here](https://www.productive-r-workflow.com/r/module1/split-your-code "link to blog post about rds (bananas)").

To address point 1, I looked up some information online about how to do it. This is what I found:

git status - shows if there are any changes

git add . - stages changes

git rm -r --cached 98_config/ - deletes file from tracking on online view of directory

git commit -m "removed tracking on private information, did some planning" - commits the changes to main

in the .gitignore file I added these lines:

98_config/\* - removes files in this directory, but not the directory itself

!98_config/.gitkeep -does not ignore a file I will create called .gitkeep

!98_config/README.md \# Optional: instructions for other developers - will not ignore a README file for future reference

I then created the aforementioned files.

After this, I addressed points 2 and 3 by modifying my "download_NCBI_metadata_by_taxID" to include a call that gets the scientific name from the ID, to use as naming for the output files.

In testing, I discovered that a lot more than just the scientific name comes back, and that these are pretty good metadata in their own right, so I am going to save much of them and extract the name for use in the function. I got to the point of having done "saveRDS" on this new taxonomy_information object. I am going to take a break and do the same for the final output of the function another day. The function is getting quite large, might need to split it in two, or something.

NEXT STEPS: finish of the upgrade of the function (i.e. point 3 from today), maybe split it up for simplicity, all the stuff from last week still left to do.

09/09/25 NEXT STEPS: modify the 3rd function so that it outputs in rds, take a good look to make sure 2 and 3 are right. all the other past next steps excluding fixing the github issue.

I am now done with the functions, I have all the metadata I need, there may be some improvements I want to make as doing functions is still new to me and I do have to use Claude.ai as a bit of a crutch. However, I think it is time to move onto some of the stuff from my previous NEXT STEPS notes. For example, moving onto downloading fastas. I will create a list of next steps below.

11/09/25 - I had some rough ideas of doing summary statistics about e.g. how many accessions there are for each genus, maybe a column chart, not vital tho. Now that the functions for downloading metadata is finished, I can move on to the pipeline around downloading the .fasta files. The rough outline of what I want to do for this section is like this:

1.  log back onto hawk SCW
2.  clean up my space on hawk
3.  figure out how to clone my github repo up there (so I do not have to manually download any scripts)
4.  figure out how to run R from the command line on Hawk
    1.  I know how to run a script through the terminal, i do it for my "create_notebooks.R" script
    2.  As a part of this, I want to figure out how to run an R script from slurm, may be useful
5.  create a script that will download the .fasta files directly to hawk
    1.  this cuts out storing them on my machine, its more efficient
    2.  I will be downloading both the genomic and protein fastas as I do not know which to use
6.  At first, the script will only do a few accessions
    1.  this means I can compare genomic fastas that I process through blast p to their protein fastas, if they are the same, then I might as well save the time and use theirs, when I download them all.
7.  Regardless of the results from that mini-experiment, I will set-up a script or some pipeline for turning genomic fastas into protein fastas
    1.  this could still be useful in future, i.e. if Aaron gives me more genomes from Alberto, he wont have the protein fastas, so I might as well already have that pipeline ready
    2.  I will need to decide if I want to do this through bash or R and command line or slurm
8.  I will need to figure out how to store the results of the fasta-downloading script
    1.  i.e. do I do more .rds, would that work on hawk? should it be a list object?
        1.  I think yes to both, but I'll see when I get there

        2.  A good idea is to test that on my machine before doing it on hawk, more visual so I know better what is actually happening

        3.  another thing to say is that the ideal formatting for blast p vs eggnogmapper is probably different, so I may need to store the protein or genomic fastas differently depending on what tool they are about to be processed by.

By the end of this phase of work, I want all the sequences ready to be processed through a new eggNog-mapper pipeline I will construct. It will be very similar to past ones, but with efficiency tweaks I found online, but the detail for that is for the next phase. A problem I have run into in the past is that the NCBI only returns the first 4000 results for a query. Thankfully, the 5 genera of study are all 2000 or under, so this is not a problem now. However, if I scale the opperation up, it could become problematic.

NOTE: because of how intensive doing the functions was, my notebooking for that section may be not the best, maybe it would be a good idea to write out somewhere what the functions do, step-by-step. maybe beef up the sections from earlier this week. Maybe a description of the metadata_download R script that calls all of these functions. More generally summary this week.

I tried to access hawk, I had innitial success connecting to the ssh box, however, I did not know how to get onto hawk. I tried a few more times, but each time and way I did it, it kept popping up with a "network connection timed out" message. I think that the only thing I can do is wait until later to see if whatever is causing the block is time-related. My final attempt was to use a VPN to try to connect. This was successful, meaning the error was likely with my network. I am now able to access it. There are some steps of automation I can do, found [here](https://bangoroffice365.sharepoint.com/sites/DigitalServices/SitePages/eResearch---Access-to-the-Hawk-Supercomputer.aspx), in the "connect using MobaXterm" section, under "advanced". I used "myquota" on SCW to see that I have used about 160,000M out of about 500,000M. This is enough that I will want to remove some of my old code or bring backup files down to my machine. I have identified a target for this, the "backups" folder. It contains a lot of large zip files, taking up a fair amount of space, however, this may be a case of burning everything in there to the ground and restarting. This would be much simpler once I set up the aforementioned automation steps, so that is what I plan to do next.

# Results

#### Descriptions of the 5 functions I made (not really results, but ideal for when it comes time for write up)

#### Any summary statistics for the metadata section (if I decide I want to do that)

# Conclusion

*Summary of outcomes, implications, and next steps.*

# Scientific Papers

*Relevant literature read this week.*

-   

-   

-   
