---
title: "Week 6 2025-06-16 to 2025-06-22"
author: "Tobias Nunn"
date: "2025-06-22"
categories: [pipeline, Major_Problem_1]
---

# Introduction {#seq-week6}

I have finished answering Major Problem 1 relating to data availability. I inevitably concluded that more data is required, an obvious conclusion. However, in answering this through the proper channels, I have constructed the pipeline to process the additional data I require once I can obtain it (that would be a good title for the dissertation). This will require answering Major Problem 2 relating to data processing time. This will take much time, and will be waylaid by the fact next week I am doing a course on data visualisation and after that I have a summer internship. Meaning, it may not be until late August I am able to work on this project again.

# Methods

I began this week by finishing up the write up for "week_5.qmd" and generating the final prototype heatmap. I found last year in ENS-2002 that waiting until the end to write up the portfolio is a bad idea because I end up doing so much I haven't the foggiest what I did 3/4 of a year ago. Thus, I would like to write up "Chapter 1: Constructing a Post-annotation data-manipulation pipeline" (working title) now, while it is fresh. This will be another R.project, however, this one will be an R book. I also aim to simplify and reconstruct the current data pipeline into a more refined format (currently, the whole thing is split between 7 different files, I want 1 for the main pipeline, and possibly another just for making the heatmaps so that if I want to create multiple different heatmaps from the same source, the code file does not get messy). After this is concluded, I will not have time to begin on answering Major Problem 2. In preparation for my data-visualisation course I will be doing a self-taught Python online course. I may write that up here, and treat these more generally as work diaries, more than specifically for ENS-3002 (or whatever the code for the dissertation is).

I started by reworking the data pipeline into the file "00_scripts/R_scripts/02_FULL_HOST_PIPELINE" with the aim of removing unnecessary steps and making better use of the PostgreSQL database.

Right, I dont have time for pagentry here. All of those ideas got kind of scrapped, the way things are set up make making the full pipeline a chore I do not have time for at the moment. Also, because Major Problem 2 and now 3 are not answered, the pipeline is incomplete, so that is all a bit of a mess that needs to be sorted after those two things. Instead, this week was used purely for writing up the methods into the dissertation and doing the oggy informatics python course. The write up is taking longer than I assumed it would, the granularity of detail I have to put in is annoying, but necessary. I have not done anything ground-breaking on the course, just learning the basics and doing Chapter 1.

The only special thing of interest I wish to write is the use of window functions in SQL to display tables. I innitially had problems with this, but with a bit of help it was sorted. The person giving me advice was innitially hesitent to help me use them as they are something advanced, but as this is not a method for my dissertation and just a fancier way of doing visuals, I decided learning them would be a fun exercise.

# Results {#sec-week6_results}

# Conclusions

# Scientific papers

#### Bacterial diseases of reptiles (<https://www.taylorfrancis.com/chapters/edit/10.1201/9781420004038-15/bacterial-diseases-reptiles-elliott-jacobson>)

Aeromonas, Citrobacter, Enterobacter, Escherichia, Morganella, Providencia, Pseudomonas, and Salmonella are just a few of a long list of aerobic bacteria frequently isolated from ill captive reptiles (Mayer and Frank, 1974; Jacobson, 1984a).

-   good source of information on how to add more data about reptile bacteria, one thing I will say though is that these are pathogenic to reptiles, but I genuinly cannot find any info on symbiotic bacteria for reptiles, so I am going to work with this for now

Names: Aeromonas, Citrobacter, Enterobacter, Morganella, Providencia, Pseudomonas

Codes:642, 544, 547, 581, 586, 286

but I do find myself asking "why these genera?", just because they were the first I found that someone once said were likely to have reptile information. This would be good for answering the new Major Problem 3, relating to host taxa availibity. However, I do not want to get confused while making the pipeline, so I think I will waylay this analysis until after I have constructed the pipeline using the 5 genera I already have. This means I can make answering MP3 a proper scientific comparison / analysis. Once the pipeline is setup, it will be ideal for for doing the testing for MP3 as I will be able to quickly analyse a lot of metadata.
