---
title: "Week 10 2025-09-15 to 2025-09-21"
author: "Tobias Nunn"
date: "2025-09-21"
categories:
---

# Introduction

This week is a direct continuation of the stuff I was doing last week. To recap, last week I completed these steps in my plan:

1.  log back onto hawk SCW ✅
2.  clean up my space on hawk ✅
3.  figure out how to clone my github repo up there (so I do not have to manually download any scripts) ✅
4.  figure out how to run R from the command line on Hawk ✅
    1.  I know how to run a script through the terminal, i do it for my "create_notebooks.R" script ✅
    2.  As a part of this, I want to figure out how to run an R script from slurm, may be useful ✅

Which means that these are the steps I will do in the next few weeks:

1.  create a script that will download the .fasta files directly to hawk
    1.  this cuts out storing them on my machine, its more efficient
    2.  I will be downloading both the genomic and protein fastas as I do not know which to use
2.  At first, the script will only do a few accessions ✅
    1.  this means I can compare genomic fastas that I process through prodigal to their protein fastas, if they are the same, then I might as well save the time and use theirs, when I download them all. ✅
3.  Regardless of the results from that mini-experiment, I will set-up a script or some pipeline for turning genomic fastas into protein fastas❓
    1.  this could still be useful in future, i.e. if Aaron gives me more genomes from Alberto, he wont have the protein fastas, so I might as well already have that pipeline ready
    2.  I will need to decide if I want to do this through bash or R and command line or slurm
4.  I will need to figure out how to store the results of the fasta-downloading script
    1.  i.e. do I do more .rds, would that work on hawk? should it be a list object?
        1.  I think yes to both, but I'll see when I get there

        2.  A good idea is to test that on my machine before doing it on hawk, more visual so I know better what is actually happening

        3.  another thing to say is that the ideal formatting for blast p vs eggnogmapper is probably different, so I may need to store the protein or genomic fastas differently depending on what tool they are about to be processed by.

There are two weeks until term start again, and I would at least like to be mostly done with this phase of work by then. As well as this project, I have to prepare for an unrelated small presentation I am doing, so I will need to focus up to get all of this done. I also created a list of next steps last week, this can be thought of as a next level down to the above list, as in, things I need to do either before or during the first element:

NEXT STEPS: add a progress bar to the loop for fun, file is going to need to be modified in order to run on Hawk(relative file paths will need to be modified), add text to the readme and .gitkeep for 01_inputs/04_fastas to explain why that file exists but is empty, at some point later on, I will combine all the .rds files for each individual accession into mega-rds files based on genus. I also realise I will need to upload the secrets file manually to hawk as it would not have copied in the clone, also, to fix the relative file paths thing using the "here" package.

# Methods

#### trial and error with getting stuff on hawk

I started this week by finishing the content from last week. I populated the "results section", this was just to consolidate what I had done. I did a lot last week and I do not want to find myself over extending and finding that I went too quick (with the help of Claude.ai) that I do not understand what I have done. Then, I will begin working through my NEXT STEPS list.

I found out that you can put a ".here" file in (just a blank text file with the name ".here") the directory you wish the relative path to start from. Putting this in 06_notebooks, means that I do not have to edit any existing file paths, and it should mean it will work equally on hawk and my machine. I do need to wrap all file paths in here::here() for this system to work, but only when they are being used, not when they are being created. After some error, I found that the .here file needs to be above where the package is looking for it (i.e. in the root directory "undergrad_dissertation". This means the file paths are going to need to be updated to come from there, as in, I will have to take out the "../" on the front, and replace it with "./". I do not think I need to do this recursively for all scripts (especially those that are not planned to be run on hawk) as the relative file path should only source from the .here when I wrap a file path in here::here. This means for file paths that will only run on my machine, I can skip using here and just let the relative file path come from the .proj file.

Right, that is all way too complicated, and worse, it doesnt even work. So I am biting the bullet and just moving the .Rproj file to the root, which means I am going to need to recursively change all file paths, but at this point I think this is the only thing that will work. I used this as an opportunity to clean up and archive old stuff. I took out the scripts under "01\_..." and "02\_...", because they were legacy code from before I decided to start again (again). So, I just removed numbers completely, which means I will have to more manually remember the order of files. I still need here() for the relative file paths, but it looks a lot less insane now, I did not have to do it on as many files as I thought, because I archived all the legacy scripts. I have modified "test_coomand_line.R" now so that it is a test of whether here() will chose to work on hawk, this is what I will test next, before moving onto the proper "fastafile_getter.R" script.

After loading onto hawk I found that the here package was not installed, so I am going to have to install it myself. After a fair bit of effort, I managed to make the test script work. In order to do this, I needed to:

1.  I created an area in my home directory called "/R/library/"

2.  do a "`module load R/4.4.2`

3.  I created an R session by typing "`R`" in the console

4.  I loaded a CRAN mirror using the code "`options(repos = c(CRAN = "https://cloud.r-project.org/"))`"

5.  I typed "`install.packages("here",lib="~/R/library")`" to install here

6.  I closed the R session with "`q()`"

7.  I then needed to modify the path so R could find the library with "`echo 'R_LIBS_USER=~/R/library' >> ~/.Renviron`", this made an .Renviron file which helped make the connection work

8.  I ran the script inside the "source" folder, using the code "`Rscript 00_scripts/R_scripts/test_command_line.R`".

    1.  It needs to be inside this folder because of the way here works, so running from the home directory is not currently possible

    2.  if you want to run slurm (which happens from the home folder) include a line to cd to the source directory

I did have to lean rather heavily on Claude.ai, because of the specific nature of the challenges of this section. However, I have come around on the idea of using this tool, because I just cannot find online resources that are anyway near as helpful.

I tried running "fastafile_getter.R" with the sample 5 accessions, this did not work because httr2 is also not on hawk.

Right, nothing I can do seems to work, I just cannot get httr2 to download onto hawk. I feel like trying to work this out is going to take way too long for someone of my experience with that system. So, I am reverting to running the script on my machine.

### Testing downloaded protein fastas vs blast-p

Ok, so, moving onto something I *can* work with. As mentioned in a previous entry, I can download fastas either in their genomic or protein state. I would like to see if running genomic fastas through prodigal will give the same result as just using the protein fastas. If they are different, this will then raise the question of "which do I use?", but I am going to burn that bridge when I get there.

Right, I really cannot make heads or tails of any of this, today has been a bit of a failure. I figure, "bugger it, might as well just use the NCBI protein.faa's because they do not require conversion it will be faster (and jump a step). The local samples will still have to be fed through blast or prodigal or something though.

### figuring out how to do it on hawk

With the rather invaluable help of Claude.ai, I managed to get the script to run on hawk. Yesterday, I mentioned that the block to this was getting the httr2 package installed onto hawk, because of its dependencies. Claude suggested a way to fix this, that being:

-   The use of the "singularity" container system \[[SCW-link](https://portal.supercomputing.wales/index.php/singularity/), [user-guide](https://docs.sylabs.io/guides/latest/user-guide/introduction.html#why-use-singularityce)\]. I am not really sure what this is, but I tried it and it worked.

    -   <div>

        > "Singularity [\[1\]](https://www.sylabs.io/)
        > is a container system that doesn’t need root access. Containers are a
        > set of applications and a minimal operating system bundled together in a
        > single file. They are a good way to ensure that anyone running the
        > software is using the exact same set of libraries and dependencies. This
        > is helpful to reproducible science where we want somebody else to be
        > able to recreate our results. They also allow us to run
        > newer/older/different operating systems than the one installed on the
        > host system."
        >
        > -SCW-link

        </div>

-   The first step is \<`module load singularity`\> - this loads the singularity program on hawk

-   Next, I ran \<`singularity pull docker://rocker/tidyverse:latest`\> - this downloaded an image file (.sif) to my home directory, called "tidyverse_latest.sif", this image contains a copy of R and some R packages, all the tidyverse ones included

    -   This means I did all that removing of tidyverse to use base R kind of for nothing, well, it still might be worth it in some areas and to be fair, I never could have predicted this

-   In order to run my R scripts, on hawk, I have to be in the "source" directory, so the next step is to `cd source`

-   Finally, I ran \<`singularity exec ~/tidyverse_latest.sif Rscript 00_scripts/R_scripts/fastafile_getter.R`\> - this successfully ran the mentioned R script, which just had a test amount of 5 accessions in it, placing them in the 01_inputs/04_fastas/ directory

This means that I can (finally) get around to actually sculpting that script into the final product. This is what I will attempt next, and I shall now make a list of the stuff I want to do to it:

-   add a progress bar (for my own enjoyment as it will likely not work in slurm)

-   add a line for reading in an argument, this will be the taxon ID of a genus

    -   this is then used to filter the accession list .rds so that 1 genus is run at a time

    -   this would be done using code similar to "test_command_line.R"'s `args <- commandArgs(trailingOnly = TRUE)`

-   rewrite the for loop to iterate over the list of accessions in the filtered list, calling my function "get_dataset_by_accession()" for each accession in turn

    -   I should build in some error handling so that if the function returns an error for 1 accession, it doesnt stop the for loop from continuing

-   add logging for both errors or successes, helping to address the above point

    -   I am thinking 1 log file for each genus

-   maybe a "resumability" feature, this would check to see if any accessions passed in had been run before and will skip them

    -   good for when I have to rerun errors

-   update the "saveRDS" line so that there is a top-level item in the list which contains the accession ID

-   NOTE: after I get the roughly 5K .rds files back, I will combine them by genus into mega .rds files

This file will be run from slurm, there will also be updates I need to do in slurm:

-   create the slurm script

-   add an "`#SBATCH --array=1-5`" - this will allow 5 jobs to run simultaneously inside 1 job

-   The script will have to do a few things, like `cd`-ing to the source/ directory

-   It will need to \<`module load singularity`\>

-   It will need to figure out which genus ID wants to be passed in as an argument to the script:

    -   `genus_ids=(``43668``1696 13867 33882 53335)genus_id=${genus_ids[$SLURM_ARRAY_TASK_ID-1]}`

-   It will execute the R script usinge \<`singularity exec ~/tidyverse_latest.sif Rscript 00_scripts/R_scripts/fastafile_getter.R genus_id`\>

# Results

*Key findings, observations, and data from this week's work.*

# Conclusion

*Summary of outcomes, implications, and next steps.*

# Scientific Papers

*Relevant literature read this week.*

-   

-   

-   
